#!/usr/bin/env bash

set -e

cmd_run_tests() {
  deno test --allow-read --allow-write --allow-run
}

cmd_update_snapshots() {
  deno test --allow-read --allow-write --allow-run -- --update
}

cmd_help() {
  echo "Usage: scripts/test or scripts/test --update"
  echo ""
}

case "${1}" in
  "") cmd_run_tests ;;
  update|--update|-u) cmd_update_snapshots ;;
  help|--help|-h) cmd_help ;;
  *)
    error "Unknown command: $1"
    cmd_help
    exit 1
    ;;
esac
